### ISSUE TITLE
App crashed when open

### ISSUE THREAD

**Issue by ab44gl** [binaryshrey/Dice#12]
**Here is  the error**
```
java.lang.RuntimeException: Canvas: trying to draw too large(138603712bytes) bitmap.
    at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
    at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
    at android.widget.ImageView.onDraw(ImageView.java:1367)
    at android.view.View.draw(View.java:19218)
    at android.view.View.updateDisplayListIfDirty(View.java:18168)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
    at android.view.View.draw(View.java:19221)
    at android.view.View.updateDisplayListIfDirty(View.java:18168)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:268)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:256)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at android.view.View.updateDisplayListIfDirty(View.java:18159)
    at android.view.View.draw(View.java:18946)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
    at android.view.View.draw(View.java:19221)
    at com.android.internal.policy.DecorView.draw(DecorView.java:791)
    at android.view.View.updateDisplayListIfDirty(View.java:18168)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2851)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2404)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
    at android.view.Choreographer.doCallbacks(Choreographer.java:841)
    at android.view.Choreographer.doFrame(Choreographer.java:772)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
    at android.os.Handler.handleCallback(Handler.java:794)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:6651)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by binaryshrey** [comment]
HI @abhishek44gl,
Could you share the emulator and sdk level details as well, so as to replicate the issue?

**Comment by abhishek44gl** [comment]
sdk level=32
api level=27

**Comment by binaryshrey** [comment]
Thanks, this has been fixed in the latest [release](https://github.com/binaryshrey/Dice/releases/tag/v1.1.0)
